apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: my-app-repo
  namespace: fleet-local
spec:
  repo: https://github.com/gitkrishna44/Fleet-repo
  branch: main
  targetNamespace: my-app
  helm:
    releaseName: my-app
